### ISSUE TITLE
Can't move to SD: access/space issues

### ISSUE THREAD

**Issue by davidep** [visi0nary/android_device_alps_k05ts_a#37] opened 2016-03-07 12:17 UTC
I'm runnign build#4 and I still have the same issue (not reported before) 

It seems that there are issue with the external SD.

From HereMaps's setting I can't switch storage memory (tapping does nothing)
From Apps->HereMaps->MoveYoSD I get Couldn't move app. Not enough storage space (there are 72GB free...) 
From MiXplorer I can only see the internal SD storage

I see other apps like gallery have trouble accessing files on external SD.

external SD's fs is FAT32

So far I'm workaround this issue via MountFolder app... but it's a pain as it's not only related to Here app.

**Comment by janengelmohr** [comment] 2016-03-07 16:12
Thanks for the report, I'll look into it!

**Comment by janengelmohr** [comment] 2016-03-09 09:30
Duplicate of #42

**Closed as completed by janengelmohr** 2016-03-09 09:30 UTC
Labels: bug, duplicate
